import databases.rewritten_db as r

STRINGS_EASY = []
STRINGS_MEDIUM = [r.STR_COMPLETE_VP, r.STR_COMPLETE_CFO, r.STR_COMPLETE_CJ, r.STR_COMPLETE_CEO]
STRINGS_DIFFICULT = [r.STR_COMPLETE_VP, r.STR_COMPLETE_CFO, r.STR_COMPLETE_CJ, r.STR_COMPLETE_CEO]

BOSSLESS_EXCLUDES = [r.STR_COMPLETE_VP, r.STR_COMPLETE_CFO, r.STR_COMPLETE_CJ, r.STR_COMPLETE_CEO]
BOSSBOT_HQ_NON_RELEASED_EXCLUDES = [r.STR_COMPLETE_CEO, r.STR_COLLECT_50_STOCKOPTIONS, r.STR_COLLECT_100_STOCKOPTIONS, r.STR_COLLECT_150_STOCKOPTIONS, r.STR_COLLECT_200_STOCKOPTIONS, r.STR_COLLECT_250_STOCKOPTIONS, STR_COLLECT_500_STOCKOPTIONS, r.STR_COLLECT_1000_STOCKOPTIONS]
